name: investment_manager
description: A Dart module for managing investments, tracking stock holdings, and providing guidance to maximize returns.
version: 0.1.0
repository: https://github.com/rummel-tech/investment-manager

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
